config/routes.rb
Rails.application.routes.draw do
  root to: "reservations#index"
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :user_name, presence: true
  validates :time, presence: true
  validates :menu_name, length: { maximum: 100 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.order(id: :asc)
  end

  def new
    @reservation = Reservation.new
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to root_path, notice: "予約を登録しました"
    else
      flash.now[:alert] = "予約登録に失敗しました"
      render :new
    end
  end

  def update
    reservation = Reservation.find(params[:id])
    reservation.update!(reservation_params)
    redirect_to root_path, notice: "予約を更新しました"
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    redirect_to root_path, notice: "予約を削除しました"
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_name, :time, :menu_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if @reservation.errors.any? %>
  <div>
    <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><span style="color: red;"><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <%= content_tag :div, msg, class: flash_type %>
  <hr>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary pr-5 pl-5">
    <%= link_to "Easy_appo", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_toggle" aria-controls="navbar_toggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbar_toggle">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "予約登録", new_reservation_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", "#", class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyAppo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reservations/edit.html.erb
<h1>予約変更画面</h1>
<%= render "layouts/error_messages" %>
<%= form_with model: @reservation, method: :patch, local:true do |f| %>
  <p><%= f.label :user_name %>：<%= f.text_field :user_name %></p>
  <p><%= f.label :time %>：<%= f.text_field :time %></p>
  <p><%= f.label :menu_name %>：<%= f.text_field :menu_name %></p>
  <%= f.submit "変更" %>
<% end %>

app/views/reservations/index.html.erb
<h1>予約一覧</h1>
<table>
  <thead>
    <td>No.</td>
    <td>予約者名</td>
    <td>内容</td>
  </thead>
  <% @reservations.each do |reservation| %>
    <tbody>
      <td><%= reservation.id %></td>
      <td><%= reservation.user_name %></td>
      <td><%= reservation.menu_name %></td>
      <td><%= link_to "詳細", reservation, class: "btn btn-primary" %></td>
      <td><%= link_to "変更", edit_reservation_path(reservation), class: "btn btn-success" %></td>
      <td><%= link_to "削除", reservation, method: :delete, data: {confirm: "削除しましすか？"}, class: "btn btn-danger" %></td>
    </tbody>
  <% end %>
</table>

app/views/reservations/new.html.erb
<h1>予約登録画面</h1>
<%= render "layouts/error_messages" %>
<%= form_with model: @reservation, local:true do |f| %>
  <p><%= f.label :user_name %>：<%= f.text_field :user_name %></p>
  <p><%= f.label :time %>：<%= f.text_field :time %></p>
  <p><%= f.label :menu_name %>：<%= f.text_field :menu_name %></p>
  <%= f.submit "登録" %>
<% end %>

app/views/reservations/show.html.erb
<h1>予約詳細</h1>
<table class="table table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>No.</th>
      <th>予約者名</th>
      <th>予約日時</th>
      <th>内容</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @reservation.id %></td>
      <td><%= @reservation.user_name %></td>
      <td><%= @reservation.time.to_s(:datetime_jp) %></td>
      <td><%= @reservation.menu_name %></td>
    </tr>
  </tbody>
</table>